"""Extend the lenght of the image_link for Artists as well

Revision ID: 88d8420c53fb
Revises: 2887e1391884
Create Date: 2025-01-04 15:49:43.762693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d8420c53fb'
down_revision = '2887e1391884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('website_link',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('website_link',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###
